### ISSUE TITLE
Issue when using blade helper

### ISSUE THREAD

**Issue by RealBenihime** [stephenlake/currency#3]
Hi, please help.

I'm getting 

FatalErrorException in 5058f4501f49ffc93d5923ec198f4f25d58b6879.php line 20:
syntax error, unexpected '<'

When using {{ @currency(200.00, 'USD') }}

**Comment by StephenLake** [comment]
@RealBenihime My hands are a little tied up for the next few days. Will review as soon as I've got a gap. As a work around, use the alias in your blade views for now?

@SeoFood
